### ISSUE TITLE
Unable to Open the location of download

### ISSUE THREAD

**Issue by captv89** [jaymoulin/yamete#10]
Hi I was trying to download using docker on my mac. I faced the attached error file. Any Idea wat I am doing wrong? Thanks :)

[Error.txt](https://github.com/jaymoulin/yamete/files/1642455/Error.txt)

**Comment by captv89** [comment]
I used the following code inorder to download without the above error.
`docker run --rm -ti -v path/to/download jaymoulin/yamete download -u https://domain.com/album -p`

but now i get the below msg after successfuly converting to pdf. 
`Parsing https://domain.com/album
Download https://domain.com/album success!
Converting to PDF
PDF created /root/src/../downloads/some/path/Issue-1.pdf`

but i am unable to open this location.. how to find this location??
thanks

**Comment by jaymoulin** [comment]
Command executed

`docker run --rm -ti -v /Users/Scorpion/Downloads/Docker:/root/downloads jaymoulin/yamete download -u https://www.8muses.com/comix/album/Velamma-Comics/Velamma/Issue-1 -p`

**Comment by captv89** [comment]
the error with `docker run --rm -ti -v /Users/Scorpion/Downloads/Docker:/root/downloads jaymoulin/yamete download -u https://www.8muses.com/comix/album/Velamma-Comics/Velamma/Issue-1 -p` still exist.

**Comment by captv89** [comment]
using the command `docker run --rm -ti -v path/to/download jaymoulin/yamete download -u https://domain.com/album -p` gives following success output...
`Parsing https://www.8muses.com/comix/album/Velamma-Comics/Velamma/Issue-1`
`Download https://www.8muses.com/comix/album/Velamma-Comics/Velamma/Issue-1 success!`
`Converting to PDF`
`PDF created /root/src/../downloads/8muses.com/Velamma-Comics/Velamma/Issue-1.pdf`

**Problem:** No such location exists on my computer. **So the question is where is the output .pdf getting saved?**

**Comment by jaymoulin** [comment]
You have to download the latest version to fix this (`docker pull jaymoulin/yamete`). 
The location is determined by the path you put in your command line, in your case,  `/Users/Scorpion/Downloads/Docker/8muses.com/Velamma-Comics/Velamma/Issue-1.pdf`

But first you'll have to delete your folder has it was created with bad rights

**Comment by captv89** [comment]
Working fantastic 👍 Thank you so much 👍 
Is there a way for working on making the script run recursively?
