### ISSUE TITLE
Help: Unable to download a comics with a 'list' of episode page links

### ISSUE THREAD

**Issue by crazyveez** [jaymoulin/yamete#12]
Executed command: 
`docker run --rm -ti -v /Users/Scorpion/Downloads/Docker:/root/downloads jaymoulin/yamete download -l /Users/Scorpion/Downloads/Docker/8muses_links.txt -p`

Output:
`In Command.php line 43:`
` Required parameter : url or list `
`download [-u|--url [URL]] [-l|--list [LIST]] [-p|--pdf] [-z|--zip] [-d|--drivers [DRIVERS]]`

Question: Is there a mistake in the usage command I have input?

**Comment by jaymoulin** [comment]
Wrong Usage. Your command should be : `docker run --rm -ti -v /Users/Scorpion/Downloads/Docker:/root/downloads -v /Users/Scorpion/Downloads/Docker/8muses_links.txt:/root/list.txt jaymoulin/yamete download -l /root/list.txt -p`
