### ISSUE TITLE
"docker" command not recognized

### ISSUE THREAD

**Issue by ghost** [jaymoulin/yamete#15]
docker run --rm -ti -v C:\Users\Lorenzo\Downloads\yamete-master:app\downloads jaymoulin/yamete download -l "Nuovo documento di testo.txt"
what did I do wrong?

**Comment by jaymoulin** [comment]
This is not related to Yamete. Docker seems not installed or your CLI PATH env does not include docker path. 

Maybe related to https://github.com/docker/toolbox/issues/260.

If you find this product useful, please consider donating.
