### ISSUE TITLE
Support for lolhentai.net still doesn't work 

### ISSUE THREAD

**Issue by LorenzoMattiussi** [jaymoulin/yamete#17]
$ docker run --rm -ti -v C:\Users\Lorenzo\Downloads\hentai jaymoulin/yamete download -u https://www.lolhentai.net/index?/collections/view/862-ad674ec4881efc2d4
Parsing https://www.lolhentai.net/index?/collections/view/862-ad674ec481efc2d4

In DownloadCommand.php line 83:

  Unable to parse https://www.lolhentai.net/index?/collections/view/862-ad674ec481efc2d4.
  Consider creating an issue on https://github.com/jaymoulin/yamete/issues/

AND--------------------------------------------------------------------------------------------------------

$ docker run --rm -ti -v C:\Users\Lorenzo\Downloads\hentai jaymoulin/yamete download -u https://www.lolhentai.net/index?/category/ahri#                 Parsing https://www.lolhentai.net/index?/category/ahri#

In DownloadCommand.php line 83:

  Unable to parse https://www.lolhentai.net/index?/category/ahri#.
  Consider creating an issue on https://github.com/jaymoulin/yamete/issues/

**Comment by jaymoulin** [comment]
Thanks you very much for your support and your love messages, I'm glad you like this product so much. You can support my work by adding star to the repo, donate in the sponsor button and/or buying merch at https://bit.ly/YameteeStore.

This driver is designed to download only albums, therefore you won't be able to download full category.

Please make sure your docker image is up to date before retrying to download. 
(`docker inspect jaymoulin/yamete --format='{{index .Config.Labels.version}}'` should show 1.7.0)

Also, you don't have to create a new issue, you could have just continued your previous issue (#16)

**Comment by LorenzoMattiussi** [comment]
Yes I have the lastest version but it doesn't work, I'm sorry but i can't solve the problem, if you try to download the album it works?

**Comment by jaymoulin** [comment]
![image](https://user-images.githubusercontent.com/14236493/67874251-f774aa00-fb34-11e9-9fab-0244bfa42a9b.png)
![image](https://user-images.githubusercontent.com/14236493/67874679-8bdf0c80-fb35-11e9-9fdf-7848d2284284.png)
Yes

**Comment by ghost** [comment]
Nothing same error...I don't know what to do, same files and same command

**Comment by jaymoulin** [comment]
Can't tell you anything without logs but I had a 404 at the beginning. Visiting the page solved the issue
