### ISSUE TITLE
Special characters in URLs

### ISSUE THREAD

**Issue by Uriei** [jaymoulin/yamete#18]
**Output of `docker inspect jaymoulin/yamete --format='{{index .Config.Labels.version}}'`:**

```
1.8.0
```

**Description**

The app can't download images when the URL has special characters like `'` or `&`, and probably many others.

**Steps to reproduce the issue:**
1. Try to download something like `https://myhentaigallery.com/gallery/thumbnails/14053`
2. Get many Download error like
`Download error : https://images.myhentaigrid.com/imagesgallery/images/Max And Maddie&#039;s Island Quest 1 - Jocasta/original/009.jpg`
3. Get sad about it.

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/6078221/69492465-7c888000-0ea3-11ea-890c-3c1426c0fcc6.png)

**Describe the results you expected:**
A successful download like the others without special characters in their URL

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using the Docker(Linux container) on Windows way for this.
`docker run --rm -ti -v D:/Uri/X/yamete:/app/downloads jaymoulin/yamete download -v -n -e /app/downloads/error.txt -l /app/downloads/galleries.txt`

**Comment by jaymoulin** [comment]
Thank you for reporting this bug. 

If you find this product useful, please consider donating and/or support by watching ads as much as you want on https://utip.io/femtopixel.

As each driver handle a site and each site forges its URL, it's more efficient to handle sites differently. If you can reproduce this bug somewhere else, please reopen this issue or create a new one so I can fix.
