### ISSUE TITLE
Feature Request: List Items in Realtime

### ISSUE THREAD

**Issue by smhmd** [jaymoulin/yamete#20]
**Description:** The ability to fire `yamete` on a given file as a list; the process never closes and is capable of reading new links appended to the list file, until closed. Maybe a list file is not needed in this interactive mode.  

**the problem this solves:** Accumulating links but having to start the downloading process until finished, or having more than one list file.
 
**Question:** Does `yamete` check if links are already downloaded?

**Comment by jaymoulin** [comment]
Thank you for your contribution! I understand your idea and it's quite interesting.

If you find this product useful, consider donating to help me continue supporting this soft!

P.S. Yamete does not check if a link as already been downloaded, it just downloads what it is asked to. One valuable reason behind this behaviour is, some URL often add chapters and it might interfere with updating those. But, as file name format is expected to be the same, you could be able to perform a check afterwards.
