### ISSUE TITLE
Love your program

### ISSUE THREAD

**Issue by Stahlhelm-TV** [jaymoulin/yamete#21]
Thank you for your program, I'd love to support you where can I do this?

**Comment by jaymoulin** [comment]
I'm glad you love this product, you can support my work by donating on the following platforms:

[![Watch Ads](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/utip.png "Watch Ads")](https://utip.io/femtopixel) [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/femtopixel)

Or buy shirt(s) on https://yametee.store
