### ISSUE TITLE
 Unable to parse

### ISSUE THREAD

**Issue by frederik2000x** [jaymoulin/yamete#28]
$ winpty docker run --rm -ti -v /app -u $(id -u) jaymoulin/yamete download -u [https://www.simply-hentai.com/league-of-legends/riven-x-zac/page/1568250]
Parsing [https://www.simply-hentai.com/league-of-legends/riven-x-zac/page/1568250]

In DownloadCommand.php line 115:

  Unable to parse [https://www.simply-hentai.com/league-of-legends/riven-x-za
  c/page/1568250].
  Consider creating an issue on https://github.com/jaymoulin/yamete/issues/

download [-u|--url [URL]] [-l|--list [LIST]] [-i|--interactive] [-p|--pdf] [-z|--zip] [-e|--errors [ERRORS]] [-d|--drivers [DRIVERS]]

**Comment by jaymoulin** [comment]
Don't use brackets when passing your URL

If you like this product, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))
