### ISSUE TITLE
Didn't find any file on the path

### ISSUE THREAD

**Issue by Imon621** [jaymoulin/yamete#31]
**Output of `docker inspect jaymoulin/yamete --format='{{index .Config.Labels.version}}'`:**

```
 1.15.1
```

**Description**

I run this docker command <b>docker run --rm -ti -v H:/programme-files/programme-files/test/app/exe/epf jaymoulin/yamete download -u  https://nhentai.net/g/329172/</b><br/>It shows Download https://nhentai.net/g/329172/ success! but I didn't find any file on H:\programme-files\programme-files\test\app\exe\epf

**There should be the files that I have downloaded. I have used docker toolbox. Also i don't have any experience with docker. **

![{60A1F4C3-5650-4D37-BAAC-C33911553683} png](https://user-images.githubusercontent.com/71474018/93544322-95f14000-f97f-11ea-8318-5f550d0b9438.jpg)
![{0F7793DC-72FA-497A-B07D-6BC476EB4ADE} png](https://user-images.githubusercontent.com/71474018/93544328-9b4e8a80-f97f-11ea-9cad-03fe91d8c876.jpg)

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

You forgot to mount your volume **IN** the download path in your container. Use this command instead: `docker run --rm -ti -v H:/programme-files/programme-files/test/app/exe/epf:/app/downloads jaymoulin/yamete download -u https://nhentai.net/g/329172/`
