### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by whitehathackerxl** [jaymoulin/yamete#32]
whenvever i download resource from a link, i get this error
PHP Warning:  require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\yamete\download on line 3

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\yamete\download on line 3
PHP Fatal error:  require_once(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\yamete\download on line 3

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\yamete\download on line 3
does anyone also have this error? i'm using windows 10 home

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

How to install :https://jaymoulin.me/me/yamete/. I suggest you use Docker to avoid installation error: https://github.com/jaymoulin/yamete#docker
