### ISSUE TITLE
Consider updating to PHP 7.2

### ISSUE THREAD

**Issue by jaymoulin** [jaymoulin/yamete#7]

**Comment by jaymoulin** [comment]
Have to reopen due to this bug : https://github.com/paquettg/php-html-parser/pull/126

**Comment by captv89** [comment]
Hi I was trying to download using docker on my mac. I faced the attached error file. Any Idea wat I am doing wrong? Thanks :)

[Error.txt](https://github.com/jaymoulin/yamete/files/1642455/Error.txt)

**Comment by jaymoulin** [comment]
@captv89 Please open your own issue for this!
